### ISSUE TITLE
Flat rate pricing for venues

### ISSUE THREAD

**Issue by NorthIsUp** [leetucker/django-danceschool#27]
currently per hour pricing is available, we have venues that are priced as "$400 for the evening" regardless of the exact hours.

**Comment by leetucker** [comment]
I'm on board with integrating this, but I want to make sure that we do it in an intelligent way.  I imagine that we won't ever cover every pricing scenario, and it's always possible to use the Expense Reporting form or to create your own app that submits expense items using a cron script.  But, this is what seems like it would make sense to me as default behavior.

Add a select field to the Location model (and to the Room model, which is being created--see the "room" branch) called "Apply rate as" with choices:
- Per hour (default)
- Per day of scheduled classes
- Per week
- Per month
- Do not generate expense items for this location

For weekly and monthly pricing, the reported allocation date will be the beginning of the period in question.

The one thing that won't be easily possible with pricing other than hourly pricing is allocating venue expense items to individual series.  So, the "Financial Performance by Event" view's line items won't reflect rental expenses if rental is not per hour.  But, I think that this limitation can just be clarified in the help text for the select field, as well as in that summary view.  Maybe later on we can think about how to allocate those types of expenses better.

Any thoughts or objections?

**Comment by leetucker** [comment]
Alright, this was a _much_ bigger pain to get implemented than I realized it would be at the outset, but this feature is all set.  Also, per #37 , the logic for this is now part of a parent model class, so that it's easy to generalize the logic used to apply to event staff and (eventually) other types of repeated expenses as well.

I've done some relatively extensive testing to think about edge case issues with this, but it's relatively complicated functionality, so @NorthIsUp , definitely let me know if you run into any significant issues.
