### ISSUE TITLE
Recurring series

### ISSUE THREAD

**Issue by NorthIsUp** [leetucker/django-danceschool#31]
We have weekly open practices, so it would be nice to "set it and forget it"

Also, our series are always at the same day and time, so making it easier to input that.

like a 'repeat for <N> weeks' option.

**Comment by leetucker** [comment]
Just to clarify, are you looking to set up a separate event for each week, so that you can run separate online registration for each?  Or are you just looking to add a new occurrence to a single event each week?  The default behavior when adding occurrences using the Series and Public Event admin forms is to add the new occurrence one week after the prior occurrence.  Is that bit of Javascript working for you?

I don't think that _infinitely_ reoccurring events would be easy to implement for this project, but I do think that for events with a single occurrence, it would be nice to have a shortcut that created multiple identical Events at once, offset in their start time by 1 or more weeks.  Is that what you're looking for?

Boston Lindy Hop is also starting up an assisted practice session on top of our classes, and we want each week's practice session to be a separate Event so that we can handle registrations for them separately, so this is something that we would use as well.  If I've described what you're looking for, let me know and I can try to implement it while I'm getting things ready for our guided practice setup.

Incidentally, if you really want something that is completely "set it and forget it," you could also add a recurring task using Huey.  At Boston Lindy Hop, we do something similar to this for nightly offsite backups.  In your custom app, just add a file called tasks.py, and put something like this in it:

    from huey import crontab
    from huey.contrib.djhuey import periodic_task, db_periodic_task, db_task
    from danceschool.core.models import PublicEvent, EventOccurrence

    @db_periodic_task(crontab(day_of_week='2'))
    def createOpenPracticeEvent():
        existing_events = PublicEvent.objects.filter(
            title='Open Practice',
            eventoccurrence__startTime==<x weeks into the future>,
        )
        if not existing_events.exists():
            new_event = PublicEvent.objects.create(title='Open Practice',<other options>)
            EventOccurrence.objects.create(event=new_event, startTime=<x weeks into the future>, endTime=<x weeks plus 1 hour>)

**Comment by leetucker** [comment]
@NorthIsUp: A secondary related question is: how should the registration page deal with Events that are simply weekly repeats of one another?  Right now, each Event shows up individually on the registration page, and if there are multiple EventOccurrences associated with that Event, those are listed within the Event's listing.  However, if you are, say, listing your practice sessions for several months in advance, but making a separate Event for them for each week so that you can store registration data for each of them, then that is going to end up looking very cluttered using the current default template.

I think that the answer is that there should to be something like a PublicEventCategory level option to list all Events in that category with the same name _as if_ they were a single event on the registration page.  So, for example, for something like a practice session, you add your practice session events to the "Practice Session" category, and they show up as if they were a single event labeled "Tuesday Practice Session," "Thursday Practice Session," etc.   The list of occurrences for each name is just the full set of occurrences for all scheduled Events in that category, with that name.

Any PublicEvent that doesn't have a category, or that has a category without the "displayAsSingleEvent" option checked, will just continue to show up as they do now, with listed Events separated by whether registration is enabled or disabled.

Thoughts on this?  We also want this feature for Boston Lindy Hop, so I'm inclined to try to implement it sooner than later.

**Comment by leetucker** [comment]
I'm actually almost done working on an admin action that will make it easy for you to repeat actual events (not just occurrences), on any multiple of days/weeks/months.  The basic code is all there, I just need to test it to make sure that it works as expected and that it handles things like daylight savings time appropriately.  Then I need to update a couple of templates to make it prettier.  However, I'm guessing that I can have it posted to master by tonight.

I think that in terms of displaying your weekly practice session nicely on your registration page, that may still be a situation where you have to override the default template for your "Practice Session" events category or whatever.  The changes that I pushed yesterday will make it much easier for you to do that, just create a copy of the template ``core/registration/event_category__default.html``, name it ``core/registration/event_category_practice-session.html`` (assuming that's the slug for your practice session category) and modify it however you'd like.

**Comment by NorthIsUp** [comment]
well then, <3

**Comment by leetucker** [comment]
OK, the admin action to create repeated series and/or events is created and working.

I'm going to go ahead and close this.  Although in principle it seems like it would be nice to have a "built-in" way to show related events one time on the registration page, rather than having them show up individually, such a feature seems to be a little at odds with allowing category-specific template overrides.

Maybe in the medium term, a better plan would be to write a post somewhere that gives an example of how to make (and where to put) a template that shows practice sessions differently on the registration page.  At some point, when I'm able to setup a Github pages branch for this, we can think about that.
